
jupyterhub:
  enabled: true

reana:
  enabled: true

  postgres:
    enabled: true

  workspaces:
    retention_rules:
      maximum_period: forever
      cronjob_schedule: "0 2 * * *"  # everyday at 2am
    paths:
      - /var/reana:/var/reana

  shared_storage:
    backend: nfs
    volume_size: 1
    access_modes: ReadWriteMany

  secrets:
    login:
      escape-iam:
        # TODO: set this
        consumer_key: "testkey"
        consumer_secret: "testsecret"

  components:
    reana_ui:
      enabled: true
      local_users: false
    reana_db:
      enabled: false
    reana_server:
      environment:
        REANA_USER_EMAIL_CONFIRMATION: false
    # reana_workflow_controller:
    #   image: docker.io/mdonadoni/reana-workflow-controller:0.9.1-7e03f0a-cvmfs
    # reana_job_controller:
    #   image: docker.io/reanahub/reana-job-controller-htcondorcern-slurmcern:0.9.1
    reana_workflow_controller:
      imagePullPolicy: IfNotPresent
      image: docker.io/reanahub/reana-workflow-controller:0.9.4
      environment:
        SHARED_VOLUME_PATH: "/var/reana/"
        REANA_JOB_STATUS_CONSUMER_PREFETCH_COUNT: 10


  compute_backends:
    - "kubernetes"
    # - "htcondorcern"
    # - "slurmcern"

  notifications:
    enabled: false
    # email_config:
    #   receiver: escape-cern-ops@cern.ch
    #   sender: escape-cern-ops@cern.ch
    #   login: ""
    #   smtp_server: cernmx.cern.ch
    #   smtp_port: 25

  reana_hostname: "reana-vre.obsuks4.unige.ch"

  db_env_config:
    REANA_DB_NAME: "reana"
    REANA_DB_PORT: "5432"
    REANA_DB_HOST: "postgres-postgresql"
    # There are two more environment variables that should be set in order
    # to connect to a database:
    # REANA_DB_USERNAME: containing the database user name.
    # REANA_DB_PASSWORD: containing the password for the user previously set.
    # Both environment variables should be set inside a Kubernetes secret:
    # `[release-name]-db`

  login:
    - name: "escape-iam"
      type: "keycloak"
      config:
        title: "ESCAPE IAM"
        base_url: "https://iam-escape.cloud.cnaf.infn.it"
        realm_url: "https://iam-escape.cloud.cnaf.infn.it"
        auth_url: "https://iam-escape.cloud.cnaf.infn.it/authorize"
        token_url: "https://iam-escape.cloud.cnaf.infn.it/token"
        userinfo_url: "https://iam-escape.cloud.cnaf.infn.it/userinfo"

  ingress:
    enabled: false

  traefik:
    enabled: false

  quota:
    default_disk_limit: 10737418240  # bytes (10 GiB)
    default_cpu_limit: 36000000      # milliseconds (10 hours)


nfs-server-provisioner:
  enabled: true
  persistence:
    enabled: true
    storageClass: standard
    size: 100M
  storageClass:

    name: cern-vre-shared-volume-storage-class
    # name: reana-infrastructure-volume-storage-class
    mountOptions:
    - tcp
    - nfsvers=4.1
    - retrans=2
    - timeo=30
  tolerations:
  - effect: NoSchedule
    key: CriticalAddonsOnly
    operator: "Exists"
