repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
    - id: helm-docs-built
      args:
        - "--chart-search-root=./vre"

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
    - id: helmlint
      args:
        - "--chart-dir=vre"

  - repo: local
    hooks:
    - id: kubeconform
      name: Validate Helm templates with kubeconform
      files: &render_inputs ^(vre/|scripts/|\.trivyignore|\.pre-commit-config\.yaml$)
      exclude: &skip_docs ^vre/README\.md$
      entry: bash -o pipefail -c '
        mkdir -p "$HOME/.cache/kubeconform";
        helm template vre ./vre -f vre/linter_values.yaml --kube-version 1.31.0 | kubeconform -strict -ignore-missing-schemas -kubernetes-version 1.31.0 -cache "$HOME/.cache/kubeconform" -summary -output pretty - '
      language: system
      pass_filenames: false

    - id: trivy-config
      name: Scan the chart for misconfiguration
      files: *render_inputs
      exclude: *skip_docs
      entry: ./scripts/scan.sh
      language: system
      pass_filenames: false
