repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli

  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
    - id: helm-docs-built
      args:
        - "--chart-search-root=./vre"
