apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: escape-vre
deploy:
  helm:
    releases:
      - name: escape-vre
        namespace: escape-vre
        createNamespace: true
        chartPath: vre
        valuesFiles:
         - vre/values.yaml
         - vre/values-custom.yaml
        version: 0.1.0-dev0
