{{- if .Values.reana.ingress_override | default true -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    ingress.kubernetes.io/ssl-redirect: "true"
    meta.helm.sh/release-name: reana
    meta.helm.sh/release-namespace: reana
    traefik.frontend.entryPoints: http,https
  name: reana-ingress
  namespace: reana
spec:
  ingressClassName: traefik
  tls:
  - secretName: cert-manager-tls-ingress-secret-reana
    hosts:
    - {{ .Values.reana.reana_hostname }}
  rules:
  - host: {{ .Values.reana.reana_hostname }}
    http:
      paths:
      - backend:
          service:
            name: reana-server
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: reana-server
            port:
              number: 80
        path: /oauth
        pathType: Prefix
      - backend:
          service:
            name: reana-ui
            port:
              number: 80
        path: /
        pathType: Prefix


{{- end -}}
