{{- if .Values.bootstrap.enabled }}
# {{ include "escape-vre.fullname" . }}-bootstrap-sa

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "escape-vre.fullname" . }}-bootstrap-sa
---
# {{ include "escape-vre.fullname" . }}-bootstrap-role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "escape-vre.fullname" . }}-bootstrap-role
# what the Job's kubectl calls need
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "escape-vre.fullname" . }}-admin-access-token"]
  verbs: ["get"]
---
# {{ include "escape-vre.fullname" . }}-bootstrap-role-binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "escape-vre.fullname" . }}-bootstrap-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "escape-vre.fullname" . }}-bootstrap-sa
roleRef:
  kind: Role
  name: {{ include "escape-vre.fullname" . }}-bootstrap-role
  apiGroup: rbac.authorization.k8s.io



{{- end }}
